// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnrXpmLJ6XRt23wmo9ESjZtOvxphhzX60',
    appId: '1:767231916991:web:6962b6ac1449ca3ad27f0a',
    messagingSenderId: '767231916991',
    projectId: 'radicalcare-33516',
    authDomain: 'radicalcare-33516.firebaseapp.com',
    storageBucket: 'radicalcare-33516.appspot.com',
    measurementId: 'G-H5GGL1YZ69',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDka5bXIHk45SPlFqawo6mnU7BVIQYJE68',
    appId: '1:767231916991:android:e60080fa8fd9fd21d27f0a',
    messagingSenderId: '767231916991',
    projectId: 'radicalcare-33516',
    storageBucket: 'radicalcare-33516.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeP_BNn-A99ZR4gmX2TlvgPG0uNrwvF2c',
    appId: '1:767231916991:ios:61af53804222952dd27f0a',
    messagingSenderId: '767231916991',
    projectId: 'radicalcare-33516',
    storageBucket: 'radicalcare-33516.appspot.com',
    iosBundleId: 'com.example.radicalcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeP_BNn-A99ZR4gmX2TlvgPG0uNrwvF2c',
    appId: '1:767231916991:ios:61af53804222952dd27f0a',
    messagingSenderId: '767231916991',
    projectId: 'radicalcare-33516',
    storageBucket: 'radicalcare-33516.appspot.com',
    iosBundleId: 'com.example.radicalcare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnrXpmLJ6XRt23wmo9ESjZtOvxphhzX60',
    appId: '1:767231916991:web:7c69de5b8d236866d27f0a',
    messagingSenderId: '767231916991',
    projectId: 'radicalcare-33516',
    authDomain: 'radicalcare-33516.firebaseapp.com',
    storageBucket: 'radicalcare-33516.appspot.com',
    measurementId: 'G-XMW0LLW9W1',
  );

}